import { chromium } from '@playwright/test';
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const types = { '.js': 'text/javascript', '.css': 'text/css', '.svg': 'image/svg+xml', '.html': 'text/html' };
const server = createServer(async (req, res) => { try { const name = req.url.split('?')[0]; const file = path.join(process.cwd(), 'dist', name === '/' ? 'index.html' : name); const data = await readFile(file); res.setHeader('Content-Type', types[path.extname(file)] || 'application/octet-stream'); res.end(data); } catch { res.statusCode = 404; res.end(); } });
await new Promise(r => server.listen(4178, '127.0.0.1', r));
const browser = await chromium.launch({ headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1100 }, deviceScaleFactor: 1 });
  await page.route('https://**/*', route => route.fulfill({ status: 200, contentType: route.request().resourceType() === 'stylesheet' ? 'text/css' : 'text/javascript', body: '' }));
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('http://127.0.0.1:4178', { waitUntil: 'networkidle' });
  await page.screenshot({ path: 'tests/guiji-desktop.png', fullPage: true });
  assert.equal(await page.locator('.stat-value').first().textContent(), '42份');
  await page.getByRole('textbox', { name: '搜索用户名', exact: true }).fill('gzpenpen');
  assert.equal(await page.locator('.user-table tbody tr').count(), 1);
  await page.getByRole('button', { name: '查看 gzpenpen 的内容' }).click();
  assert.equal(await page.locator('.detail-file-list>div').count(), 5);
  await page.getByRole('button', { name: '关闭弹窗', exact: true }).click();
  await page.getByRole('button', { name: '清空搜索', exact: true }).click();
  await page.getByRole('checkbox', { name: '选择 gzpenpen', exact: true }).check();
  await page.getByRole('checkbox', { name: '选择 Asternminate', exact: true }).check();
  await page.getByRole('button', { name: '合并所选' }).click();
  await page.getByRole('button', { name: '确认合并 (2)' }).click();
  await page.locator('.main-nav').getByRole('button', { name: '合并记录' }).click();
  assert.equal(await page.locator('.history-item').count(), 1);
  await page.getByRole('button', { name: '撤销', exact: true }).click();
  assert.equal(await page.locator('.history-item').count(), 0);
  await page.locator('.main-nav').getByRole('button', { name: /待确认内容/ }).click();
  const pendingBefore = await page.locator('.review-item').count();
  await page.getByRole('button', { name: '确认归属', exact: true }).first().click();
  await page.getByText('手动编辑文本', { exact: true }).click();
  await page.getByLabel('这份内容属于谁？').fill('JoelMaud70028, Pap0927, NIUNIU6910');
  await page.getByRole('button', { name: '确认并更新统计' }).click();
  assert.equal(await page.locator('.review-item').count(), pendingBefore - 1);
  await page.getByRole('button', { name: '导出结果', exact: true }).click();
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: '导出 CSV' }).click();
  const downloaded = await download;
  console.log('Download filename:', downloaded.suggestedFilename());
  assert.ok(downloaded.suggestedFilename().endsWith('.csv'));
  const csv = await readFile(await downloaded.path(), 'utf8');
  assert.ok(csv.includes('用户名') && csv.includes('gzpenpen'));
  await page.locator('.main-nav').getByRole('button', { name: '分析概览', exact: true }).click();
  await page.getByRole('button', { name: /已经复制了文件名/ }).click();
  await page.getByRole('textbox', { name: '文件名清单', exact: true }).fill('Alice_2089930283558801756_1___.mp4\nAlice_2089930283558801757_1___.mp4\nunknown-name');
  await page.getByRole('button', { name: '开始分析' }).click();
  assert.equal(await page.locator('.stat-value').first().textContent(), '3份');
  await page.reload({ waitUntil: 'networkidle' });
  assert.equal(await page.locator('.stat-value').first().textContent(), '3份');
  await page.getByRole('button', { name: '试试示例' }).click();
  await page.locator('input[type=file]').setInputFiles({ name: 'test.txt', mimeType: 'text/plain', buffer: Buffer.from('Tester_2089930283558801756_1___.mp4\nTester_2089930283558801756_2___.mp4') });
  await page.waitForFunction(() => document.querySelector('.stat-value')?.textContent === '2份');
  await page.locator('.main-nav').getByRole('button', { name: '解析设置' }).click();
  await page.getByRole('switch', { name: '按作品 ID 去重' }).click();
  await page.locator('.main-nav').getByRole('button', { name: '用户列表' }).click();
  assert.equal(await page.locator('.amount-cell strong').first().innerText(), '1');
  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true });
  await mobile.route('https://**/*', route => route.fulfill({ status: 200, contentType: route.request().resourceType() === 'stylesheet' ? 'text/css' : 'text/javascript', body: '' }));
  await mobile.goto('http://127.0.0.1:4178', { waitUntil: 'networkidle' });
  await mobile.screenshot({ path: 'tests/guiji-mobile.png', fullPage: true });
  assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await mobile.getByRole('button', { name: '打开导航菜单' }).click();
  await mobile.locator('.main-nav').getByRole('button', { name: /待确认内容/ }).click();
  assert.ok(await mobile.locator('.review-item').count() > 0);
  await mobile.getByRole('button', { name: '确认归属', exact: true }).first().click();
  assert.equal(await mobile.getByRole('dialog').count(), 1);
  await mobile.screenshot({ path: 'tests/guiji-mobile-dialog.png', fullPage: false });
  assert.deepEqual(errors, []);
  console.log('PASS: desktop/mobile layout, search, details, merge, undo, review correction, CSV export, text import, upload, local persistence, and ID deduplication.');
} finally { await browser.close(); server.close(); }
