import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Activity, ArrowDown, ArrowDownToLine, ArrowRight, ArrowUpRight, BarChart3, Check, CheckCheck, ChevronDown, ChevronLeft, ChevronRight, CircleCheck, CircleHelp, Clipboard, Clock3, FileCheck2, FileText, Files, Fingerprint, FolderInput, GitMerge, History, Info, Layers3, LayoutDashboard, ListFilter, LoaderCircle, Menu, Plus, RotateCcw, Search, Settings2, ShieldCheck, SlidersHorizontal, Sparkles, Trash2, TriangleAlert, Upload, Users, X } from 'lucide-react';
import { Dialog } from './components/Dialog';
import { QuickMerge } from './components/QuickMerge';
import { AttributionPicker } from './components/AttributionPicker';
import { groupSuggestions, prepareMerges, type MergeRequest } from './lib/merging';
import { analyze, canonical, DEFAULT_SETTINGS, downloadFile, getSuggestions, summarize, toCsv, type FileRecord, type MergeEntry, type Settings } from './lib/analyzer';
import { SAMPLE_TEXT } from './lib/sample';

type Page = 'overview' | 'users' | 'review' | 'merges' | 'settings' | 'help';
type Modal = 'paste' | 'rules' | 'merge' | 'export' | 'reset' | null;
interface Session { text: string; name: string; sample: boolean; aliases: Record<string, string>; overrides: Record<string, string[]>; history: MergeEntry[]; settings: Settings; }
const INITIAL: Session = { text: SAMPLE_TEXT, name: '示例文件.txt', sample: true, aliases: {}, overrides: {}, history: [], settings: DEFAULT_SETTINGS };
const navItems: { id: Page; title: string; icon: typeof Layers3 }[] = [
  { id: 'overview', title: '分析概览', icon: LayoutDashboard }, { id: 'users', title: '用户列表', icon: Users },
  { id: 'review', title: '待确认内容', icon: CircleHelp }, { id: 'merges', title: '合并记录', icon: GitMerge },
];
const pageInfo: Record<Page, { title: string; subtitle: string }> = {
  overview: { title: '让每一份内容，都有迹可循。', subtitle: '导入文件清单，自动识别用户、整理合作内容，发现你的内容收藏偏好。' },
  users: { title: '你的内容，来自哪些用户？', subtitle: '查看每一位创作者的内容数量，搜索用户名，或合并同一个人的不同名称。' },
  review: { title: '有些细节，值得再确认。', subtitle: '机器不确定的地方，交给你判断。确认后的结果会实时更新到统计中。' },
  merges: { title: '不同名字，同一个人。', subtitle: '保留每一次归属调整，让用户合并有记录、可追溯，也可以随时撤销。' },
  settings: { title: '按你的习惯，理解文件。', subtitle: '明确识别规则与统计方式，让下一次分析更准确。' },
  help: { title: '从一份清单，到清晰的统计。', subtitle: '关于如何使用归集，以及它能做什么、不能做什么。' },
};
const avatarColors = ['green', 'lavender', 'blue', 'sand', 'rose', 'mint'];
function readSession(): Session {
  try { const stored = localStorage.getItem('guiji-session-v1'); if (stored) { const s = JSON.parse(stored); if (typeof s.text === 'string' && s.settings && s.aliases && s.overrides && Array.isArray(s.history)) return s; } } catch { /* The browser may block local storage. */ }
  return INITIAL;
}

export default function Workspace() {
  const [session, setSession] = useState<Session>(readSession);
  const [page, setPage] = useState<Page>('overview');
  const [modal, setModal] = useState<Modal>(null);
  const [mobileMenu, setMobileMenu] = useState(false);
  const [toast, setToast] = useState('');
  const [storageWarning, setStorageWarning] = useState(false);
  const [busy, setBusy] = useState(false);
  const [dragging, setDragging] = useState(false);
  const [pasteText, setPasteText] = useState('');
  const [search, setSearch] = useState('');
  const [tableTab, setTableTab] = useState<'all' | 'collab' | 'merged'>('all');
  const [minimum, setMinimum] = useState(0);
  const [showFilters, setShowFilters] = useState(false);
  const [ascending, setAscending] = useState(false);
  const [tablePage, setTablePage] = useState(1);
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [mergeNames, setMergeNames] = useState<string[]>([]);
  const [detailUser, setDetailUser] = useState<string | null>(null);
  const [reviewFile, setReviewFile] = useState<FileRecord | null>(null);
  const [reviewNames, setReviewNames] = useState('');
  const [reviewFilter, setReviewFilter] = useState<'all' | 'review' | 'unparsed'>('all');
  const [reviewSearch, setReviewSearch] = useState('');
  const [exportType, setExportType] = useState<'users' | 'files' | 'review'>('users');
  const fileInput = useRef<HTMLInputElement>(null);
  const records = useMemo(() => analyze(session.text, session.settings, session.overrides), [session.text, session.settings, session.overrides]);
  const users = useMemo(() => summarize(records, session.aliases, session.settings), [records, session.aliases, session.settings]);
  const suggestions = useMemo(() => getSuggestions(users), [users]);
  const suggestionGroupCount = useMemo(() => groupSuggestions(suggestions).length, [suggestions]);
  const attributionNames = useMemo(() => [...new Set([...users.flatMap(user => [user.name, ...user.aliases]), ...session.settings.knownNames.split(/[,，\n]/).map(name => name.trim()).filter(Boolean)])], [users, session.settings.knownNames]);
  const pending = records.filter(r => r.status !== 'parsed');
  const parsed = records.filter(r => r.status === 'parsed').length;
  const unparsedCount = records.filter(r => r.status === 'unparsed').length;
  const collabs = records.filter(r => new Set(r.users.map(u => canonical(u, session.aliases))).size > 1).length;
  const totalContributions = users.reduce((sum, u) => sum + u.count, 0);
  const progress = records.length ? Math.round(parsed / records.length * 100) : 0;
  const duplicateCount = records.length - new Set(records.map(r => r.filename)).size;
  const currentUser = users.find(u => u.name === detailUser);
  const filteredUsers = useMemo(() => { const filtered = users.filter(u => (u.name.toLowerCase().includes(search.toLowerCase()) || u.aliases.some(a => a.toLowerCase().includes(search.toLowerCase()))) && (tableTab !== 'collab' || u.collaborations > 0) && (tableTab !== 'merged' || u.aliases.length > 0) && u.count >= minimum); return ascending ? [...filtered].reverse() : filtered; }, [users, search, tableTab, minimum, ascending]);
  const pageSize = 6;
  const pageCount = Math.max(1, Math.ceil(filteredUsers.length / pageSize));
  const visibleUsers = filteredUsers.slice((tablePage - 1) * pageSize, tablePage * pageSize);
  const filteredReview = pending.filter(r => (reviewFilter === 'all' || r.status === reviewFilter) && r.filename.toLowerCase().includes(reviewSearch.toLowerCase()));
  const maxCount = users[0]?.count || 1;
  useEffect(() => { try { localStorage.setItem('guiji-session-v1', JSON.stringify(session)); setStorageWarning(false); } catch { setStorageWarning(true); } }, [session]);
  useEffect(() => { if (!toast) return; const timeout = setTimeout(() => setToast(''), 4200); return () => clearTimeout(timeout); }, [toast]);
  useEffect(() => { setTablePage(1); }, [search, tableTab, minimum, ascending]);
  useEffect(() => { if (tablePage > pageCount) setTablePage(pageCount); }, [pageCount, tablePage]);
  const closeModal = useCallback(() => setModal(null), []);
  const closeDetail = useCallback(() => setDetailUser(null), []);
  const closeReview = useCallback(() => setReviewFile(null), []);

  function navigate(next: Page) { setPage(next); setMobileMenu(false); setSelected(new Set()); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  function loadData(text: string, name: string, sample = false) {
    if (!text.trim()) { setToast('没有找到内容，请先添加文件名。'); return; }
    setSession(s => ({ ...s, text, name, sample, aliases: {}, overrides: {}, history: [] }));
    setSelected(new Set()); setSearch(''); setTableTab('all'); setMinimum(0); setTablePage(1); setModal(null); setPage('overview');
    setToast(sample ? '示例已载入，可以体验分析与手动确认。' : `已分析 ${name}，共 ${analyze(text, session.settings).length} 条内容。`);
  }
  async function handleFiles(files: FileList | null) {
    if (!files?.length) return;
    const list = Array.from(files);
    if (list.some(file => !/\.(txt|csv|log)$/i.test(file.name))) { setToast('请选择 TXT、CSV 或 LOG 文本文件。'); return; }
    if (list.reduce((sum, f) => sum + f.size, 0) > 10 * 1024 * 1024) { setToast('文件总大小需小于 10 MB，请拆分后导入。'); return; }
    setBusy(true);
    try {
      const texts = await Promise.all(list.map(async f => { const buffer = await f.arrayBuffer(); const utf8 = new TextDecoder('utf-8').decode(buffer); return utf8.includes('\uFFFD') ? new TextDecoder('gb18030').decode(buffer) : utf8; }));
      loadData(texts.join('\n'), list.length === 1 ? list[0].name : `${list[0].name} 等 ${list.length} 个文件`);
    } catch { setToast('读取文件失败，请确认它是 UTF-8 或 GBK 编码的文本文件。'); }
    finally { setBusy(false); if (fileInput.current) fileInput.current.value = ''; }
  }
  function openMerge(names: string[] = [...selected]) { setMergeNames(names); setModal('merge'); }
  function merge(requests: MergeRequest[], keepOpen: boolean) {
    try {
      const { aliases, entries } = prepareMerges(session.aliases, requests, users.map(user => user.name));
      if (!entries.length) return false;
      setSession(s => ({ ...s, aliases, history: [...s.history, ...entries] }));
      setSelected(new Set());
      if (!keepOpen) setModal(null);
      setToast(entries.length === 1 ? `已将 ${entries[0].names.length} 个名称归集到 ${entries[0].target}，可撤销。` : `已分别合并 ${entries.length} 组用户，可在合并记录中逐次撤销。`);
      return true;
    } catch (error) { setToast(error instanceof Error ? error.message : '合并失败，请重新选择。'); return false; }
  }
  function undoMerge() { const last = session.history[session.history.length - 1]; if (!last) return; setSession(s => ({ ...s, aliases: last.previous, history: s.history.slice(0, -1) })); setToast('已撤销最近一次合并，统计已恢复。'); }
  function editFile(record: FileRecord) { setReviewFile(record); setReviewNames(record.users.join(', ')); }
  function saveReview() {
    if (!reviewFile) return;
    const names = reviewNames.split(/[,，\n]/).map(n => n.trim().replace(/^@/, '')).filter(Boolean);
    if (!names.length) { setToast('请至少填写一个用户名。'); return; }
    setSession(s => ({ ...s, overrides: { ...s.overrides, [reviewFile.id]: names } })); setReviewFile(null); setToast('归属已确认，用户统计已更新。');
  }
  function exportCsv() {
    let rows: (string | number)[][];
    if (exportType === 'users') rows = [['用户名', '内容数量', '合作内容', '待确认内容', '合并别名'], ...users.map(u => [u.name, u.count, u.collaborations, u.pending, u.aliases.join(' / ')])];
    else rows = [['文件名', '用户名', '状态', '识别规则', '备注'], ...(exportType === 'review' ? pending : records).map(r => [r.filename, r.users.map(u => canonical(u, session.aliases)).join(' / '), r.status === 'parsed' ? '已确认' : r.status === 'review' ? '待确认' : '无法识别', r.kind, r.reason])];
    downloadFile(toCsv(rows), `guiji-${exportType}-${new Date().toISOString().slice(0, 10)}.csv`, 'text/csv;charset=utf-8'); setModal(null); setToast('CSV 已导出，可以用 Excel 或 Numbers 打开。');
  }
  function toggleSelect(name: string) { setSelected(s => { const next = new Set(s); if (next.has(name)) next.delete(name); else next.add(name); return next; }); }

  const renderUserTable = (full = false) => <section className={`panel users-panel ${full ? 'full-table' : ''}`}>
    <div className="panel-heading"><div className="section-heading"><h2>用户内容排行</h2><span className="count-label">{users.length} 位用户</span></div><button className="text-button muted" onClick={() => openMerge()}><GitMerge size={15} />合并用户</button></div>
    <div className="table-tabs"><div className="tab-group">{([['all', '全部用户'], ['collab', '合作用户'], ['merged', '已合并']] as const).map(([id, label]) => <button key={id} className={tableTab === id ? 'active' : ''} onClick={() => setTableTab(id)}>{label}{id === 'all' && <span>{users.length}</span>}</button>)}</div><span className="table-unit">单位：{session.settings.dedupePosts ? '作品' : '份内容'}</span></div>
    <div className="table-tools"><label className="search-input"><Search size={16} /><input aria-label="搜索用户名" placeholder="搜索用户名或别名…" value={search} onChange={e => setSearch(e.target.value)} />{search && <button aria-label="清空搜索" onClick={() => setSearch('')}><X size={14} /></button>}</label><button className={`button button-small ${showFilters ? 'filter-active' : ''}`} onClick={() => setShowFilters(!showFilters)}><ListFilter size={15} />筛选{minimum > 0 && <span className="filter-dot" />}</button></div>
    {showFilters && <div className="filter-bar"><span>内容数量至少</span><select aria-label="最少内容数" value={minimum} onChange={e => setMinimum(Number(e.target.value))}><option value="0">不限</option><option value="2">2 份</option><option value="3">3 份</option><option value="5">5 份</option><option value="10">10 份</option></select><button className="text-button" onClick={() => { setMinimum(0); setSearch(''); setTableTab('all'); }}>重置筛选</button></div>}
    {selected.size > 0 && <div className="selection-bar"><span>已选择 {selected.size} 位用户</span><button onClick={() => openMerge()} disabled={selected.size < 2}>合并所选 <GitMerge size={13} /></button><button aria-label="取消选择" onClick={() => setSelected(new Set())}><X size={15} /></button></div>}
    <div className="table-scroll"><table className="user-table"><thead><tr><th className="checkbox-col"><input type="checkbox" aria-label="选择本页全部用户" checked={visibleUsers.length > 0 && visibleUsers.every(u => selected.has(u.name))} onChange={e => { const checked = e.target.checked; setSelected(s => { const next = new Set(s); visibleUsers.forEach(u => checked ? next.add(u.name) : next.delete(u.name)); return next; }); }} /></th><th className="rank-col">排名</th><th>用户名</th><th className="amount-col"><button onClick={() => setAscending(!ascending)}>内容数<ArrowDown size={12} className={ascending ? 'rotated' : ''} /></button></th><th className="collab-col">合作</th><th className="status-col">状态</th><th className="action-col" /></tr></thead><tbody>{visibleUsers.map((u, index) => <tr key={u.name} className={selected.has(u.name) ? 'selected-row' : ''}>
      <td><input type="checkbox" aria-label={`选择 ${u.name}`} checked={selected.has(u.name)} onChange={() => toggleSelect(u.name)} /></td><td><span className={`rank ${users.indexOf(u) < 3 ? `rank-${users.indexOf(u) + 1}` : ''}`}>{String(users.indexOf(u) + 1).padStart(2, '0')}</span></td><td><button className="username-cell" onClick={() => setDetailUser(u.name)}><span className={`avatar ${avatarColors[(index + (tablePage - 1) * pageSize) % avatarColors.length]}`}>{u.name.slice(0, 2).toUpperCase()}</span><span className="username-text">{u.name}{u.aliases.length > 0 && <small>{u.aliases.length} 个别名已归集</small>}</span></button></td><td><div className="amount-cell"><strong>{u.count}</strong><span className="mini-track"><span style={{ width: `${u.count / maxCount * 100}%` }} /></span></div></td><td className="collab-col">{u.collaborations || <span className="dash">—</span>}</td><td className="status-col"><span className={`status-badge ${u.pending ? 'pending' : 'confirmed'}`}><span />{u.pending ? '待确认' : u.aliases.length ? '已合并' : '已识别'}</span></td><td><button className="icon-button row-action" aria-label={`查看 ${u.name} 的内容`} onClick={() => setDetailUser(u.name)}><ChevronRight size={16} /></button></td>
    </tr>)}</tbody></table>{!visibleUsers.length && <div className="empty-state"><Search size={30} /><h3>没有找到匹配的用户</h3><p>试试其他关键词，或调整筛选条件。</p><button className="text-button" onClick={() => { setSearch(''); setMinimum(0); setTableTab('all'); }}>清除筛选</button></div>}</div>
    <div className="table-footer"><span>共 {filteredUsers.length} 位用户{filteredUsers.length > 0 && <>，显示 {(tablePage - 1) * pageSize + 1}–{Math.min(tablePage * pageSize, filteredUsers.length)}</>}</span><div className="pagination"><button aria-label="上一页" disabled={tablePage <= 1} onClick={() => setTablePage(p => p - 1)}><ChevronLeft size={15} /></button>{Array.from({ length: Math.min(pageCount, 3) }, (_, i) => { const n = tablePage <= 2 ? i + 1 : Math.min(tablePage - 1 + i, pageCount - 2 + i); return <button key={n} className={n === tablePage ? 'active' : ''} onClick={() => setTablePage(n)}>{n}</button>; })}{pageCount > 3 && tablePage < pageCount - 1 && <span>…</span>}<button aria-label="下一页" disabled={tablePage >= pageCount} onClick={() => setTablePage(p => p + 1)}><ChevronRight size={15} /></button></div></div>
  </section>;

  return <div className="app-shell">
    {mobileMenu && <div className="mobile-overlay" onClick={() => setMobileMenu(false)} />}
    <aside className={`sidebar ${mobileMenu ? 'is-open' : ''}`}>
      <button className="brand" onClick={() => navigate('overview')} aria-label="归集首页"><span className="brand-icon"><Layers3 size={25} strokeWidth={1.8} /></span><span>归集<span className="brand-latin">GUIJI</span></span></button>
      <div className="workspace-picker"><span className="workspace-avatar">我</span><div><strong>我的内容空间</strong><span>个人工作台</span></div><span className="local-tag">本地</span></div>
      <div className="nav-label">工作空间 <span>WORKSPACE</span></div>
      <nav className="main-nav">{navItems.map(item => <button key={item.id} className={page === item.id ? 'active' : ''} onClick={() => navigate(item.id)}><item.icon size={19} strokeWidth={1.7} /><span>{item.title}</span>{item.id === 'review' && pending.length > 0 && <span className="nav-count">{pending.length}</span>}{page === item.id && <span className="nav-active-dot" />}</button>)}</nav>
      <div className="nav-divider" /><nav className="main-nav secondary-nav"><button className={page === 'settings' ? 'active' : ''} onClick={() => navigate('settings')}><SlidersHorizontal size={18} strokeWidth={1.7} /><span>解析设置</span></button><button className={page === 'help' ? 'active' : ''} onClick={() => navigate('help')}><CircleHelp size={18} strokeWidth={1.7} /><span>使用帮助</span></button></nav>
      <div className="sidebar-bottom"><div className="privacy-card"><span className="privacy-icon"><ShieldCheck size={21} strokeWidth={1.7} /></span><h3>你的数据，只属于你</h3><p>所有解析均在浏览器本地完成，<br />文件内容不会上传到服务器。</p><span><span className="green-dot" />本地处理 · 安心使用</span></div><div className="sidebar-footer"><span className="small-brand">归集 <span>v1.0</span></span><button aria-label="打开使用帮助" onClick={() => navigate('help')}><CircleHelp size={16} /></button></div></div>
    </aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="mobile-menu icon-button" aria-label="打开导航菜单" onClick={() => setMobileMenu(true)}><Menu size={21} /></button><span className="desktop-crumb">工作空间</span><ChevronRight size={14} className="desktop-crumb" /><strong>{navItems.find(n => n.id === page)?.title || (page === 'settings' ? '解析设置' : '使用帮助')}</strong></div><div className="topbar-right"><span className="local-status"><span className="green-dot" />所有数据仅保存在本地</span><span className="topbar-divider" /><button className="help-top" onClick={() => navigate('help')}><CircleHelp size={16} /><span>使用指南</span><ArrowUpRight size={13} /></button></div></header>
    <main>
      <div className="page-heading"><div><div className="eyebrow"><span />{page === 'overview' ? 'A LITTLE ORDER, A LOT OF CLARITY' : 'YOUR COLLECTION, CONNECTED'}</div><h1>{pageInfo[page].title}</h1><p>{pageInfo[page].subtitle}</p></div>{page === 'overview' || page === 'users' || page === 'review' ? <button className="button export-button" disabled={!records.length} onClick={() => setModal('export')} aria-label="导出结果"><ArrowDownToLine size={16} /><span>导出结果</span><ChevronDown size={14} /></button> : null}</div>
      {storageWarning && <div className="notice warning"><TriangleAlert size={16} />浏览器存储空间不足，当前结果尚未保存。请导出备份后再关闭页面。</div>}
      {page === 'overview' && <>
        <section className="panel import-panel"><div className="panel-heading"><div className="section-heading"><span className="section-number">01</span><h2>导入内容清单</h2><span className="subtle-label">整理，从一份 TXT 开始</span></div><button className="text-button" onClick={() => loadData(SAMPLE_TEXT, '示例文件.txt', true)}><Sparkles size={14} />试试示例<ArrowUpRight size={13} /></button></div>
          <div className="import-grid"><div className={`drop-zone ${dragging ? 'dragging' : ''}`} onDragOver={e => { e.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={e => { e.preventDefault(); setDragging(false); handleFiles(e.dataTransfer.files); }}><div className="file-art"><span className="file-back" /><span className="file-front"><span className="file-fold" /><span className="file-art-lines" /><span className="file-txt">TXT</span></span><span className="file-upload-badge"><ArrowUpRight size={13} /></span></div><div className="drop-copy"><h3>把 TXT 文件拖到这里</h3><p>或点击选择文件，开始整理你的内容</p><div className="drop-action"><button className="button button-primary" onClick={() => fileInput.current?.click()} disabled={busy}>{busy ? <LoaderCircle size={15} className="spin" /> : <Plus size={16} />}{busy ? '正在解析…' : '选择文件'}</button><span>支持 .txt · 最大 10 MB</span></div></div></div>
          <button className="paste-card" onClick={() => { setPasteText(''); setModal('paste'); }}><span className="paste-icon"><Clipboard size={23} strokeWidth={1.5} /></span><div><h3>已经复制了文件名？</h3><p>直接粘贴文本，也能轻松分析</p><span>粘贴文本<ArrowRight size={15} /></span></div></button></div>
          <div className="import-footnote"><span><ShieldCheck size={13} />无需上传视频或图片，仅需包含文件名的文本清单</span><button onClick={() => setModal('rules')}>支持哪些命名格式？<ArrowUpRight size={12} /></button></div>
        </section>
        <div className="analysis-context"><div><span className="green-dot" /><strong>{session.sample ? '示例分析' : '分析结果'}</strong><span className="context-divider" /><FileText size={13} /><span className="current-filename">{session.name}</span><span className="sample-pill">{session.sample ? '示例数据' : '本地文件'}</span></div><span className="context-right"><CheckCheck size={14} /><span>分析完成</span><span className="context-divider" /><span>{records.length} 条记录</span></span></div>
        <div className="stats-grid">
          <div className="stat-card"><div className="stat-top"><span>内容总数</span><span className="stat-icon neutral"><Files size={18} /></span></div><div className="stat-value">{records.length}<span>份</span><span className="stat-sparkline" aria-hidden="true"><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /></span></div><p>本次导入的全部内容文件</p></div>
          <button className="stat-card" onClick={() => navigate('users')}><div className="stat-top"><span>识别用户</span><span className="stat-icon green"><Users size={18} /></span></div><div className="stat-value">{users.length}<span>位</span></div><p><span className="tiny-green-dot" />含待确认归属的用户 <ArrowUpRight size={13} /></p></button>
          <button className="stat-card" onClick={() => { navigate('users'); setTableTab('collab'); }}><div className="stat-top"><span>多人合作内容</span><span className="stat-icon purple"><GitMerge size={18} /></span></div><div className="stat-value">{collabs}<span>份</span></div><p>占全部内容的 <strong>{records.length ? (collabs / records.length * 100).toFixed(1) : 0}%</strong></p></button>
          <button className="stat-card amber-card" onClick={() => navigate('review')}><div className="stat-top"><span>需要你确认</span><span className="stat-icon amber"><CircleHelp size={18} /></span></div><div className="stat-value">{pending.length}<span>份</span></div><p>有些名字，需要再认识一下 <ArrowRight size={14} /></p></button>
        </div>
        <button className={`unparsed-summary ${unparsedCount ? '' : 'no-errors'}`} onClick={() => { navigate('review'); setReviewFilter('unparsed'); setReviewSearch(''); }}><TriangleAlert size={16} /><span><strong>无法识别 {unparsedCount} 份</strong> · {unparsedCount ? '原始文件名已保留，点击补充归属' : '没有遗漏条目；存疑归属仍需确认'}</span><ChevronRight size={15} /></button>
        <div className="results-grid">{renderUserTable()}<div className="insights-column">
          <section className="panel overview-panel"><div className="panel-heading"><h2>解析概况</h2><button className="icon-button" aria-label="查看解析规则" onClick={() => setModal('rules')}><Info size={15} /></button></div><div className="overview-body"><div className="donut-wrap"><div className="donut" role="img" aria-label={`已明确识别 ${progress}%`} style={{ background: `conic-gradient(#398263 0 ${progress}%, #ecc478 ${progress}% ${records.length ? (records.length - records.filter(r => r.status === 'unparsed').length) / records.length * 100 : 0}%, #d7dcd7 0 100%)` }}><div><strong>{progress}<span>%</span></strong><span>已明确识别</span></div></div><span className="donut-note"><Check size={11} />分析已完成</span></div><div className="chart-legend"><div><span><i className="legend-dot green" />已明确识别</span><strong>{parsed}<small>份</small></strong></div><div><span><i className="legend-dot amber" />需要确认</span><strong>{records.filter(r => r.status === 'review').length}<small>份</small></strong></div><div><span><i className="legend-dot gray" />无法识别</span><strong>{records.filter(r => r.status === 'unparsed').length}<small>份</small></strong></div></div></div><div className="overview-note"><Info size={13} /><span>待确认内容已计入初步排行，确认后更准确。</span></div></section>
          <section className="merge-hint"><div className="merge-hint-top"><span className="merge-hint-icon"><GitMerge size={19} /></span><span className="soft-badge">让统计更准确</span></div><h3>不同用户名，可能是同一个人</h3><p>{suggestionGroupCount ? `发现 ${suggestionGroupCount} 组相似名称，支持一键确认、多选分组分别合并。` : '名字相似不等于同一个人。选中你认识的用户，将多个别名归集在一起。'}</p><button className="button" onClick={() => openMerge()}>{suggestionGroupCount ? '查看疑似相同用户' : '检查并合并用户'}<ArrowRight size={14} /></button><span className="hint-footnote"><History size={12} />每次合并可追溯，也可撤销</span></section>
        </div></div>
        <div className="bottom-note"><Info size={13} /><span>统计说明：合作内容会分别计入每位用户，因此用户内容数之和可能大于文件总数。{duplicateCount > 0 && `检测到 ${duplicateCount} 条重复文件名，按导入条目计数。`}</span><button onClick={() => setModal('rules')}>了解解析规则<ArrowUpRight size={12} /></button></div>
      </>}
      {page === 'users' && <><div className="users-summary"><span><Users size={18} /><strong>{users.length}</strong> 位用户</span><span><Files size={18} /><strong>{totalContributions}</strong> 次用户内容归属</span><span><GitMerge size={18} /><strong>{Object.keys(session.aliases).length}</strong> 个已合并别名</span><button className="button button-primary" onClick={() => openMerge()}><GitMerge size={15} />合并用户</button></div>{renderUserTable(true)}<div className="bottom-note"><Info size={14} />同一份合作内容会计入每位参与用户。待确认归属也会暂时计入排行。</div></>}
      {page === 'review' && <><div className="notice warning"><TriangleAlert size={17} /><div><strong>先确认，再下结论</strong><p>仅凭下划线无法可靠区分「一个带下划线的用户名」与「多位合作用户」。点击候选标签即可调整归属；当前统计包含这些推测结果。</p></div></div><section className="panel review-panel"><div className="panel-heading"><div className="section-heading"><h2>待确认清单</h2><span className="count-label">{pending.length} 份内容</span></div><button className="text-button" onClick={() => setModal('rules')}><Settings2 size={14} />识别规则</button></div><div className="review-count-note">归属存疑 {pending.length - unparsedCount} 份 · 无法识别 {unparsedCount} 份（未计入用户排行，确认后自动补入）</div><div className="review-tools"><div className="segmented">{([['all', '全部'], ['review', '归属存疑'], ['unparsed', '无法识别']] as const).map(([id, label]) => <button key={id} className={reviewFilter === id ? 'active' : ''} onClick={() => setReviewFilter(id)}>{label}<span>{id === 'all' ? pending.length : id === 'unparsed' ? unparsedCount : pending.length - unparsedCount}</span></button>)}</div><label className="search-input"><Search size={15} /><input placeholder="搜索文件名…" aria-label="搜索待确认文件" value={reviewSearch} onChange={e => setReviewSearch(e.target.value)} /></label></div><div className="review-list">{filteredReview.map(r => <div key={r.id} className="review-item"><span className={`review-file-icon ${r.status === 'unparsed' ? 'error' : ''}`}><FileText size={21} /></span><div className="review-item-info"><div className="file-name">{r.filename}</div><p>{r.reason}</p><div className="user-chips">{r.users.map(name => <span key={name}>@{canonical(name, session.aliases)}</span>)}<span className="kind-chip">{r.kind}</span></div></div><button className="button button-small" onClick={() => editFile(r)}>确认归属<ChevronRight size={13} /></button></div>)}{!filteredReview.length && <div className="empty-state"><CircleCheck size={38} /><h3>{pending.length ? '没有匹配的内容' : '所有归属都清晰了'}</h3><p>{pending.length ? '试试其他关键词或筛选条件。' : '这份清单暂时没有需要手动确认的项目。'}</p></div>}</div></section></>}
      {page === 'merges' && <><div className="notice neutral-notice"><GitMerge size={18} /><span>合并只会调整统计归属，不会修改你的原始文件名。同一份内容合并后不会重复计入同一用户。</span><button className="button button-primary button-small" onClick={() => openMerge()}><Plus size={14} />新建合并</button></div><section className="panel"><div className="panel-heading"><div className="section-heading"><h2>合并历史</h2><span className="count-label">{session.history.length} 条记录</span></div><span className="subtle-label">按时间倒序排列</span></div>{session.history.length ? <div className="history-list">{[...session.history].reverse().map((entry, i) => <div className="history-item" key={entry.id}><span className="history-symbol"><GitMerge size={20} /></span><div><div className="history-names">{entry.names.join(' + ')}<ArrowRight size={16} /><strong>{entry.target}</strong></div><p><Clock3 size={12} />{new Date(entry.at).toLocaleString('zh-CN')}<span>手动确认合并</span></p></div>{i === 0 ? <button className="button button-small" onClick={undoMerge}><RotateCcw size={14} />撤销</button> : <span className="subtle-label">请先撤销较新的记录</span>}</div>)}</div> : <div className="empty-state spacious"><span className="empty-icon"><GitMerge size={30} /></span><h3>还没有合并过用户</h3><p>如果同一位用户使用了不同的名字，可以在这里把它们归集起来。</p><button className="button button-primary" onClick={() => openMerge()}><Plus size={15} />创建第一次合并</button></div>}</section></>}
      {page === 'settings' && <div className="settings-grid"><section className="panel settings-panel"><div className="panel-heading"><h2>解析与统计</h2><span className="saved-indicator"><Check size={13} />自动保存</span></div><div className="setting-item"><div><h3>按作品 ID 去重</h3><p>关闭时，每一条文件名计为一份内容。开启后，同一用户相同作品 ID 的多个分集或图片只统计一次。</p></div><button role="switch" aria-checked={session.settings.dedupePosts} aria-label="按作品 ID 去重" className={`toggle ${session.settings.dedupePosts ? 'on' : ''}`} onClick={() => setSession(s => ({ ...s, settings: { ...s.settings, dedupePosts: !s.settings.dedupePosts } }))}><span /></button></div><div className="setting-item vertical"><h3>已知完整用户名</h3><p>每行一个用户名。解析时优先将这些名字视为一个整体，保留名字中的下划线。已手动确认的文件不会被重新拆分。</p><textarea className="text-area names-area" aria-label="已知完整用户名" placeholder={'例如：\nhigher_animal\ng_mguy\nqiuming_ss'} value={session.settings.knownNames} onChange={e => setSession(s => ({ ...s, settings: { ...s.settings, knownNames: e.target.value } }))} /><span className="input-helper"><Info size={13} />修改会立即重新分析当前清单，不会自动合并用户。</span></div><div className="setting-item"><div><h3>本地数据管理</h3><p>清空当前清单、手动修正、合并历史和设置。此操作无法撤销。</p></div><button className="button danger-button" onClick={() => setModal('reset')}><Trash2 size={15} />清空数据</button></div></section><section className="panel settings-about"><span className="large-shield"><ShieldCheck size={31} /></span><h2>本地优先，隐私优先。</h2><p>归集不会将文件内容发送到服务器。所有文件分析和统计都在当前浏览器中运行。</p><ul><li><Check size={15} />无须登录或创建账号</li><li><Check size={15} />自动保存到当前浏览器</li><li><Check size={15} />支持导出 CSV，数据随你带走</li></ul><div className="notice neutral-notice">请注意：清理浏览器数据或使用无痕模式可能导致记录丢失，重要结果请及时导出。</div></section></div>}
      {page === 'help' && <div className="help-grid"><section className="panel help-panel"><div className="panel-heading"><h2>三步，把内容整理清楚</h2><span className="soft-badge">快速开始</span></div>{[{ title: '准备一份文件名清单', text: '把文件名保存为 TXT 文本，每行一个；也支持用空格分隔多条媒体文件名。只需要名称，不需要上传原视频或图片。', icon: FolderInput }, { title: '查看统计，确认模糊归属', text: '系统从右侧识别作品 ID、UUID 或随机下载标识，提取前方用户名。遇到含下划线的名称或多人合作，会标记不确定的拆分供你确认。', icon: Fingerprint }, { title: '归集别名，导出你的结果', text: '在用户列表勾选两个或更多名字，确认它们是同一个人后合并。随时导出用户排行、文件明细或待确认清单。', icon: BarChart3 }].map((item, i) => <div className="help-step" key={item.title}><span className="help-step-num">0{i + 1}</span><div><h3><item.icon size={17} />{item.title}</h3><p>{item.text}</p></div></div>)}<div className="help-actions"><button className="button button-primary" onClick={() => { navigate('overview'); fileInput.current?.click(); }}><Upload size={15} />导入我的清单</button><button className="button" onClick={() => loadData(SAMPLE_TEXT, '示例文件.txt', true)}>先试试示例<ArrowRight size={15} /></button></div></section><section className="panel faq-panel"><div className="panel-heading"><h2>你可能想知道</h2></div>{[{ q: '为什么用户内容数加起来比文件多？', a: '一份多人合作内容会分别计入每位参与者。例如 A 与 B 合作的一份视频，会为 A 和 B 各增加 1 份内容，所以总归属次数可能大于文件数。' }, { q: '能完全自动区分用户名中的下划线吗？', a: '不能。仅凭文件名，这些信息存在歧义。归集会给出推测，但把歧义标记出来。你可以手动确认，或在解析设置中添加已知的完整用户名。' }, { q: '疑似相同用户是如何判断的？', a: '系统会寻找忽略大小写、下划线和连字符后相同，或仅有一个字符差异的名字。这只是文字相似性，不代表真实身份；所有合并都需要你手动确认。大清单只对内容数前 350 位用户提供相似建议，所有用户仍可手动合并。' }, { q: '同一作品的 _1 和 _2 会重复计数吗？', a: '默认按文件条目计数，两条算两份。如果希望它们按一个作品统计，请在解析设置中开启“按作品 ID 去重”。' }, { q: '支持什么编码和文件大小？', a: '支持总大小不超过 10 MB 的 TXT、CSV 和 LOG 文本，优先读取 UTF-8，遇到乱码会尝试 GBK。CSV 仅支持单列文件名清单，不支持多字段表格。' }].map(item => <details key={item.q}><summary>{item.q}<ChevronDown size={15} /></summary><p>{item.a}</p></details>)}</section></div>}
      <footer className="main-footer"><span><Layers3 size={13} />归集，让内容井井有条。</span><span>少一点手动整理，多一点清晰。<span className="footer-leaf">✳</span></span></footer>
    </main></div>
    <input ref={fileInput} type="file" accept=".txt,.csv,.log,text/plain" multiple hidden onChange={e => handleFiles(e.target.files)} />
    {modal === 'paste' && <Dialog title="粘贴你的文件清单" subtitle="每行一个文件名，也支持以空格分隔多个媒体文件名。" onClose={closeModal}><div className="notice neutral-notice"><ShieldCheck size={15} />文本只在当前浏览器中分析，不会上传。</div><textarea className="text-area paste-textarea" value={pasteText} onChange={e => setPasteText(e.target.value)} placeholder={'把文件名粘贴在这里…\n\n用户名_2089930283558801756_1___.mp4\n用户A_用户B_2081002921140068704_1___.mp4'} aria-label="文件名清单" /><div className="dialog-bottom"><span className="input-helper">导入会替换当前清单及合并记录</span><button className="button button-primary" disabled={!pasteText.trim()} onClick={() => loadData(pasteText, '粘贴的文本.txt')}><Activity size={15} />开始分析</button></div></Dialog>}
    {modal === 'rules' && <Dialog title="先认识名字，再整理内容" subtitle="识别规则透明可查，无法确定的内容不会被悄悄忽略。" onClose={closeModal}><div className="rule-list"><div><span>01</span><section><h3>优先识别右侧作品标识</h3><p>支持 13 位数字标识、14–22 位数字作品 ID、_1 / _2 / _NA 后缀、UUID 和大小写扩展名，以及可含下划线、连字符的 15–16 位随机下载标识。也支持「用户名_6–32 位字母数字或连字符标识___清晰度」格式，忽略 720p、1080p、4K 等清晰度后缀。可用换行、空格或逗号分隔文件名，括号编号前的空格会保留。</p><code>lp_puppy_1783063467550___.mp4 → lp_puppy（待确认）</code><code>yangmoyum_K0cGCSlRIn9RhPv___.mp4 → yangmoyum</code><code>chao188_uTcIyP6___720p.mp4 → chao188</code></section></div><div><span>02</span><section><h3>谨慎拆分用户名</h3><p>优先匹配设置中的已知用户名，并参考重复前缀。已加入 higher_animal、g_mguy、S_men2024、qiuming_ss、KamuiHY_X、lp_puppy 作为完整名称候选，单条导入也能保留下划线。缺少分隔符时，尝试从候选名称后提取 16–17 位下载标识。存疑归属可点击标签调整，也能搜索补全；不会自动合并身份。</p><code>KamuiHY_X + Jann49224729 + ZAKEmuscle → 待确认</code><code>qiuming_ssfiLNemMMvkYS3bMMs___.mp4 → qiuming_ss（待确认）</code></section></div><div><span>03</span><section><h3>不丢掉无法解析的文件</h3><p>不符合规则的条目会保留原始文件名，并单独显示「无法识别」数量。点击进入清单，选择候选标签或补充用户名，确认后就会纳入排行。</p></section></div><div><span>04</span><section><h3>统计口径由你掌握</h3><p>默认每条记录计为一份内容；合作内容对每人计一次。可按作品 ID 去重。对于「_2 (83)」这类序号与重名编号，仅移除编号后推测归属，不将编号当作作品 ID，因此即使开启去重也按文件条目统计，避免误合并不同作品。</p><code>inbedwithrowie_make1ovenotfri_2 (83)___.mp4 → 两位候选用户（待确认）</code></section></div></div><div className="dialog-bottom"><span className="input-helper">机器提供线索，你保留决定权。</span><button className="button button-primary" onClick={() => { setModal(null); navigate('settings'); }}>调整解析设置<ArrowRight size={14} /></button></div></Dialog>}
    {modal === 'merge' && <QuickMerge users={users} suggestions={suggestions} initialNames={mergeNames} canUndo={session.history.length > 0} onMerge={merge} onUndo={undoMerge} onClose={closeModal} />}
    {modal === 'export' && <Dialog title="带走你的整理成果" subtitle="导出为 UTF-8 CSV，可直接在 Excel、Numbers 或其他表格工具中打开。" onClose={closeModal}><div className="export-options">{([{ id: 'users', icon: Users, title: '用户统计排行', text: `${users.length} 位用户 · 内容数量、合作数、待确认数量与别名` }, { id: 'files', icon: FileCheck2, title: '全部文件明细', text: `${records.length} 份内容 · 原始文件名、用户归属与解析状态` }, { id: 'review', icon: CircleHelp, title: '待确认内容清单', text: `${pending.length} 份内容 · 保留存疑原因，方便逐条核对` }] as const).map(option => <label key={option.id} className={exportType === option.id ? 'selected' : ''}><span className="export-option-icon"><option.icon size={21} /></span><span><strong>{option.title}</strong><small>{option.text}</small></span><input type="radio" name="exportType" value={option.id} checked={exportType === option.id} onChange={() => setExportType(option.id)} /></label>)}</div><div className="dialog-bottom"><span className="input-helper"><ShieldCheck size={13} />在本地生成，无需上传</span><button className="button button-primary" onClick={exportCsv}><ArrowDownToLine size={15} />导出 CSV</button></div></Dialog>}
    {modal === 'reset' && <Dialog title="确定清空本地数据？" subtitle="当前导入的清单、用户合并、手动确认与自定义规则都将被移除。此操作无法撤销。" onClose={closeModal}><div className="notice warning"><TriangleAlert size={17} />建议先导出结果，保留你的整理成果。</div><div className="dialog-bottom"><button className="button" onClick={closeModal}>保留数据</button><button className="button button-danger" onClick={() => { setSession({ ...INITIAL, text: '', name: '尚未导入文件', sample: false }); setModal(null); navigate('overview'); setToast('本地数据已清空。你可以重新导入清单。'); }}><Trash2 size={15} />确认清空</button></div></Dialog>}
    {currentUser && <Dialog wide title={currentUser.name} subtitle={`${currentUser.count} 份内容 · ${currentUser.collaborations} 份合作内容 · ${currentUser.pending} 份待确认归属`} onClose={closeDetail}>{currentUser.aliases.length > 0 && <div className="notice neutral-notice"><GitMerge size={15} />已合并别名：{currentUser.aliases.join('、')}</div>}<div className="detail-file-list">{currentUser.files.map(r => <div key={r.id}><FileText size={19} /><section><span className="file-name">{r.filename}</span><p>{r.users.map(u => canonical(u, session.aliases)).filter((u, i, all) => all.indexOf(u) === i).join(' · ')}</p></section><button className={`status-badge ${r.status !== 'parsed' ? 'pending' : 'confirmed'}`} onClick={() => { setDetailUser(null); editFile(r); }}>{r.status !== 'parsed' ? '去确认' : '修改归属'}<ChevronRight size={12} /></button></div>)}</div><div className="dialog-bottom"><span className="input-helper">原始文件名完整保留，归属可随时调整。</span><button className="button" onClick={closeDetail}>关闭</button></div></Dialog>}
    {reviewFile && <Dialog title="确认这份内容的归属" subtitle="用户名已拆成候选标签，点击即可添加、移除或组合；也可以搜索补全。" onClose={closeReview}><div className="review-original"><FileText size={20} /><code>{reviewFile.filename}</code></div><div className={`notice ${reviewFile.status !== 'parsed' ? 'warning' : 'neutral-notice'}`}><Info size={16} />{reviewFile.reason}</div><AttributionPicker key={reviewFile.id} record={reviewFile} value={reviewNames} onChange={setReviewNames} knownNames={attributionNames} /><div className="input-helper"><Info size={13} />用户名中的下划线会原样保留，多个名字将计为合作。</div><div className="dialog-bottom"><button className="button" onClick={closeReview}>稍后再看</button><button className="button button-primary" disabled={!reviewNames.trim()} onClick={saveReview}><Check size={15} />确认并更新统计</button></div></Dialog>}
    {toast && <div className="toast" role="status"><CircleCheck size={18} /><span>{toast}</span><button aria-label="关闭通知" onClick={() => setToast('')}><X size={15} /></button></div>}
  </div>;
}
